### ISSUE TITLE
Database structure proposal

### ISSUE THREAD

**Issue by vlanse** [vlanse/plan_b#1]
Quick and dirty proposal for database structure

```
proposed database structure

production_calendars:
	year: int
	data: blob                 // yaml with description

teams
	id: bigint
	name: varchar(255)
	type: int                  // qa or dev team

people
	id: bigint
	type: int                  // permanent, to-be-hired
	firstname: varchar(255)
	lastname: varchar(255)
	team_id: bigint            // link to team
	works_since: date
	efficiency: float

releases
	id: bigint
	name: varchar(255)
	deadline: date
		unique key: name

data_sources:
	id: bigint
	name: varchar(255)
	type: int // jira for now
	url: varchar(255)

data_queries
	id: bigint
	data_source_id: bigint      // link to data source
	query: varchar(255)

release_queries                 // data query to release corresponds as 1:1
	release_id: bigint
	data_query_id: bigint
		unique key: (release_id, data_query_id)


// tables with historical data:

issues
	date: date
	key: varchar(255)
	type: bigint
	url: varchar(255)
	created: date
	resolved: date
	due: date
	summary: varchar(255)
	components: varchar(255)
	assignee: varchar(255)
	reporter: varchar(255)
	status: varchar(255)
	owner_team_id: int          // link to owner team
	data_query_id: bigint       // link to data query -> release
		unique key: (date, key)

original_estimates:
	date: date
	issue_key: key              // link to issue (with date)
	team_id: bigint             // link to team
	reqs_level: int
	design_level: int
	arch_design: float
	perf_design: float
	implementation: float
	documentation: float
	qa_effort: float
		unique key: (date, issue_key, team_id)	

remaining_estimates
	date: date
	issue_key: key              // link to issue (with date)
	team_id: bigint             // link to team
	reqs_level: int
	design_level: int
	arch_design: float
	perf_design: float
	implementation: float
	documentation: float
	qa_effort: float
		unique key: (date, issue_key, team_id)

// table that holds time allocations for each team, added manually

team_time_allocations
	date: date                   // date when allocation has been saved
	team_id: bigint              // link to team
	item_type: int               // release (for dev and qa teams) or issue (for qa teams)
	item_name                    // dynamic link to release (via name) or issue (via key)
	month: int                   // month number
	allocation: float            // time allocation
		unique key: (date, team_id, item_type, item_name)
```

**Comment by perfguru87** [comment]
Hi, my 2 cents:

1) bigint seems redundant everywhere except primary key for the 'issues' table

2) I'd rename all tables to 'singular' (for example person instead of people) to have natural name of foreign keys

3) comments/examples for every field would make sense for newcomers

4) ideas/proposals

a) people table - to add JIRA-specific person name to build/add quick links to JIRA issues

b) people table - technically a person can be assigned to a team and project within a period of time... Otherwise, if you change something (for example efficiency) it will be applied to completed projects automatically and break the results.

What I would propose:

Team - something which represents the org chart. There could be dev-team-A, dev-team-B, arch-team, perf-team, sec-team, ...

A person is assigned to team and project withing a time range.

project: // immutable
	id: int
	name: varchar(255) // ABC-1.0, ABC-1.1, XYZ-2.0

project_history: // mutable
         project_id: int // FK to project
         datetime: datetime // datetime when change appeared
         scope_complete_datetime: datetime // scope complete datetime
         feature_complete_datetime: datetime // feature complete datetime
         ready_to_manufacture_datetime: datetime // feature complete datetime

team: // immutable
	id: int
	name: varchar(255)

person: // immutable
	id: int
	firstname: varchar(255)
	lastname: varchar(255)
        jira_name: varchar(255) // Invan.Petrov

person_history: // mutable
        id: int
        person_id: int // FK to people
	team_id: int    // FK to team
	datetime: datetime // begin of time interval (the 'end' is either next history track or 'now')
        project_id: int // FK to project
        project_assignment: float // aka efficiency on this project: 1 - fully allocated to 'project_id', 0.3 - a newbie in project_id
               unique key: (person_id, team_id, project, project_allocation, datetime)

So when a person moves to a team or increases efficiency or reassigned to new project - the people_history record appears. The person can be allocated to 2 projects at the same time.

For example, a person works since February on project-A with project_assignment 0.3 and project-B with proeject_assignment 0.2. So in total a person would have total assignment (efficiency) as 0.5

For TBH it can be used proeject_assignment = 0.0

The 'person' table is exported from JIRA

The 'project', 'project_history', team and person_history are managed manually via a config file which can be committed to git...

Then probably the 'team_time_allocations' will not be needed
 
c) I propose the following changes around the issues:

issue_type
    id: int
    name: varchar(64) // 0 - Bug, 1 - Sub-task, ...

issues // immutable
    id: int
    key: varchar(64) // ABC-123
    url: varchar(255) // https://jira.localhost/browse/ABC-123
    created: date // 2019-01-01

issues_history: // rarely mutable
    id: bigint                      // internal id
    issue_id: int  // FK to 'issues'
    datetime: datetime // datetime of change
    type: int // FK to 'issues_type'
    resolved: datetime
    due: date
    summary: varchar(255)
    components: varchar(255)
    assignee: id // FK to person
    reporter: id // FK to person
    status: varchar(255)
    owner_team_id: int          // link to owner team
    data_query_id: int       // link to data query -> release
    reqs_level: float // 1 - hi confidence, 1.5 - med confidence, 2 - low confidence 
    design_level: float // 1 - hi confidence, 1.5 - med confidence, 2 - low confidence
          unique key: (datetime, issue_id)

original_estimates: // rarely mutable, many original_estimates per issue
    id: bigint                      // internal id
    issue_id: int                // FK to 'issues'
    datetime: datetime   // datetime of change
    team_id: int               // FK to team, it can be arch, perf, seq, QA, dev, doc, whatever team
    estimate: float          // man weeks
          unique key: (datetime, issue_id, team_id)

remaining_estimates: // frequently mutable, many remaining_estimates per issue
    id: bigint                    // FK to 'issues'
    datetime: datetime   // datetime of change
    team_id: int               // FK to team, it can be arch, perf, seq, QA, dev, doc, whatever team
    estimate: float          // man weeks
          unique key: (datetime, issue_id, team_id)

**Comment by vlanse** [comment]
Plus we need table with implementation types and we need to add implementation type to original/remaining estimate. That is because single team can work on multiple activities i.e. architecture design, performance engineering, integration testing and implementation itself

**Comment by vlanse** [comment]
not sure if we need internal ids in historical tables (i.e. issue_history.id, person_history.id). Will Postgres define such and ids automatically if we not define them? From business logic perspective such an ids look senseless IMO
